# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Myco-Core-User
version:      1
version_from: lib/Myco/Core/User.pm
installdirs:  site
requires:
    Digest::MD5:                   0
    Myco:                          0
    Myco::Core::Person:            0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
